# Generated by Django 4.2.3 on 2023-08-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffinform', '0003_alter_articles_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='URL'),
        ),
    ]
